POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "name": "pak",
    "price": "200000",
    "registerTime": "2024-01-31 15:05:59",
    "sellType" : "SELLING"
}

###
GET http://localhost:8080/products HTTP/1.1
###
GET http://localhost:8080/products/1 HTTP/1.1
###

### 첨부 파일이 있는 이슈 생성
POST http://localhost:8080/api/issues HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"
Content-Type: text/plain

첨부파일 테스트

--boundary
Content-Disposition: form-data; name="content"
Content-Type: text/plain

첨부파일 sodyd

--boundary
Content-Disposition: form-data; name="files"; filename="screenshot.png"
Content-Type: image/png

< ./files/screenshot.png
--boundary--